
DROP TABLE USERS CASCADE;
CREATE  TABLE USERS(
id            SERIAL       PRIMARY KEY,
email        VARCHAR(128) NOT NULL UNIQUE,
user_name    VARCHAR(64) NOT NULL UNIQUE,
password      VARCHAR(64) NOT NULL CONSTRAINT PASSWORD_LENGTH CHECK(char_length(password)>8),
created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
user_active BOOLEAN DEFAULT false,
email_verified    BOOLEAN DEFAULT false
);